statement ::= definition | expression

definition ::= DEFINE pattern DEFEQ expression
pattern ::= IDENTIFIER
    | LBRACKET pattern * RBRACKET
    | LBRACKET pattern (SEPERATOR (pattern | &RBRACKET))* RBRACKET
    | DISCARD

expression ::= lambda
private lambda ::= LAMBDA pattern DOT expression
